log:
    console:
        enabled: yes

modes:
    t-npm:
        type: transport
        transport: protobuf-tcp

    h-all:
        type: rpcHandler
        subset: all

    h-auth:
        type: rpcHandler
        subset: auth

    s-all:
        type: service
        subset: all

handlers:
    all: '#'

    auth:
        - RPCAuthenticateWithKeyMessage
        - RPCAuthenticateWithTokenMessage
        - RPCAuthenticateRegisterServerMessage

services:
    all:
        - avatars
        - auth
        - sessions
        - externals
        - networking

transports:
    protobuf_tcp:
        port: 3036
        desc: data_dist/proto.desc

amqp:
    url: amqp://localhost

redis:
    host: 127.0.0.1

auth:
    method: npv2

p2prelay:
    enabled: no

externals:
    citiv:
        queue: citivreq

    networking:
        queue: int-networking