# This file has been automatically generated.
ids =
	RPCHelloMessage: 1000 
	RPCAuthenticateWithKeyMessage: 1001 
	RPCAuthenticateWithDetailsMessage: 1002 
	RPCAuthenticateWithTokenMessage: 1003 
	RPCAuthenticateValidateTicketMessage: 1004 
	RPCAuthenticateKickUserMessage: 1005 
	RPCAuthenticateExternalStatusMessage: 1006 
	RPCAuthenticateResultMessage: 1010 
	RPCAuthenticateUserGroupMessage: 1011 
	RPCAuthenticateValidateTicketResultMessage: 1012 
	RPCAuthenticateRegisterServerMessage: 1021 
	RPCAuthenticateRegisterServerResultMessage: 1022 
	RPCStorageGetPublisherFileMessage: 1101 
	RPCStoragePublisherFileMessage: 1111 
	RPCStorageGetUserFileMessage: 1102 
	RPCStorageUserFileMessage: 1112 
	RPCStorageWriteUserFileMessage: 1103 
	RPCStorageWriteUserFileResultMessage: 1113 
	RPCStorageSendRandomStringMessage: 1104 
	RPCFriendsSetSteamIDMessage: 1201 
	RPCFriendsGetProfileDataMessage: 1202 
	RPCFriendsGetProfileDataResultMessage: 1203 
	RPCFriendsRosterMessage: 1211 
	RPCFriendsPresenceMessage: 1212 
	RPCFriendsSetPresenceMessage: 1213 
	RPCFriendsGetUserAvatarMessage: 1214 
	RPCFriendsGetUserAvatarResultMessage: 1215 
	RPCServersCreateSessionMessage: 1301 
	RPCServersCreateSessionResultMessage: 1302 
	RPCServersGetSessionsMessage: 1303 
	RPCServersGetSessionsResultMessage: 1304 
	RPCServersUpdateSessionMessage: 1305 
	RPCServersUpdateSessionResultMessage: 1306 
	RPCServersDeleteSessionMessage: 1307 
	RPCServersDeleteSessionResultMessage: 1308 
	RPCCloseAppMessage: 2001 
	RPCMessagingSendDataMessage: 2002 

names =
	1000: 'RPCHelloMessage'
	1001: 'RPCAuthenticateWithKeyMessage'
	1002: 'RPCAuthenticateWithDetailsMessage'
	1003: 'RPCAuthenticateWithTokenMessage'
	1004: 'RPCAuthenticateValidateTicketMessage'
	1005: 'RPCAuthenticateKickUserMessage'
	1006: 'RPCAuthenticateExternalStatusMessage'
	1010: 'RPCAuthenticateResultMessage'
	1011: 'RPCAuthenticateUserGroupMessage'
	1012: 'RPCAuthenticateValidateTicketResultMessage'
	1021: 'RPCAuthenticateRegisterServerMessage'
	1022: 'RPCAuthenticateRegisterServerResultMessage'
	1101: 'RPCStorageGetPublisherFileMessage'
	1111: 'RPCStoragePublisherFileMessage'
	1102: 'RPCStorageGetUserFileMessage'
	1112: 'RPCStorageUserFileMessage'
	1103: 'RPCStorageWriteUserFileMessage'
	1113: 'RPCStorageWriteUserFileResultMessage'
	1104: 'RPCStorageSendRandomStringMessage'
	1201: 'RPCFriendsSetSteamIDMessage'
	1202: 'RPCFriendsGetProfileDataMessage'
	1203: 'RPCFriendsGetProfileDataResultMessage'
	1211: 'RPCFriendsRosterMessage'
	1212: 'RPCFriendsPresenceMessage'
	1213: 'RPCFriendsSetPresenceMessage'
	1214: 'RPCFriendsGetUserAvatarMessage'
	1215: 'RPCFriendsGetUserAvatarResultMessage'
	1301: 'RPCServersCreateSessionMessage'
	1302: 'RPCServersCreateSessionResultMessage'
	1303: 'RPCServersGetSessionsMessage'
	1304: 'RPCServersGetSessionsResultMessage'
	1305: 'RPCServersUpdateSessionMessage'
	1306: 'RPCServersUpdateSessionResultMessage'
	1307: 'RPCServersDeleteSessionMessage'
	1308: 'RPCServersDeleteSessionResultMessage'
	2001: 'RPCCloseAppMessage'
	2002: 'RPCMessagingSendDataMessage'

snames =
	1000: 'HelloMessage'
	1001: 'AuthenticateWithKeyMessage'
	1002: 'AuthenticateWithDetailsMessage'
	1003: 'AuthenticateWithTokenMessage'
	1004: 'AuthenticateValidateTicketMessage'
	1005: 'AuthenticateKickUserMessage'
	1006: 'AuthenticateExternalStatusMessage'
	1010: 'AuthenticateResultMessage'
	1011: 'AuthenticateUserGroupMessage'
	1012: 'AuthenticateValidateTicketResultMessage'
	1021: 'AuthenticateRegisterServerMessage'
	1022: 'AuthenticateRegisterServerResultMessage'
	1101: 'StorageGetPublisherFileMessage'
	1111: 'StoragePublisherFileMessage'
	1102: 'StorageGetUserFileMessage'
	1112: 'StorageUserFileMessage'
	1103: 'StorageWriteUserFileMessage'
	1113: 'StorageWriteUserFileResultMessage'
	1104: 'StorageSendRandomStringMessage'
	1201: 'FriendsSetSteamIDMessage'
	1202: 'FriendsGetProfileDataMessage'
	1203: 'FriendsGetProfileDataResultMessage'
	1211: 'FriendsRosterMessage'
	1212: 'FriendsPresenceMessage'
	1213: 'FriendsSetPresenceMessage'
	1214: 'FriendsGetUserAvatarMessage'
	1215: 'FriendsGetUserAvatarResultMessage'
	1301: 'ServersCreateSessionMessage'
	1302: 'ServersCreateSessionResultMessage'
	1303: 'ServersGetSessionsMessage'
	1304: 'ServersGetSessionsResultMessage'
	1305: 'ServersUpdateSessionMessage'
	1306: 'ServersUpdateSessionResultMessage'
	1307: 'ServersDeleteSessionMessage'
	1308: 'ServersDeleteSessionResultMessage'
	2001: 'CloseAppMessage'
	2002: 'MessagingSendDataMessage'

exports.pids = ids
exports.pnames = names
exports.snames = snames